-- Supabase SQL Editor에서 실행

create table if not exists public.study_progress (
  user_id uuid primary key references auth.users(id) on delete cascade,
  current_day integer not null default 1,
  current_index integer not null default 0,
  day_score integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.answer_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id text not null,
  day_number integer not null,
  step text not null,
  result text not null check (result in ('correct','wrong','unsure')),
  answered_at timestamptz not null default now(),
  unique(user_id, question_id)
);

create table if not exists public.review_items (
  user_id uuid not null references auth.users(id) on delete cascade,
  concept_key text not null,
  ease numeric not null default 2.5,
  interval_days integer not null default 1,
  repetitions integer not null default 0,
  last_reviewed_at timestamptz,
  next_review_at timestamptz,
  primary key(user_id, concept_key)
);

-- 사용자가 계속 추가하는 민법 참고자료
create table if not exists public.study_sources (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subject text not null default '민법',
  title text not null,
  tags text[] not null default '{}',
  source_text text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists study_sources_user_subject_idx
on public.study_sources(user_id, subject, updated_at desc);

alter table public.study_progress enable row level security;
alter table public.answer_log enable row level security;
alter table public.review_items enable row level security;
alter table public.study_sources enable row level security;

create policy "progress own row" on public.study_progress
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "answers own rows" on public.answer_log
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "reviews own rows" on public.review_items
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "sources own rows" on public.study_sources
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
